validation_checklist:
  login_password:
    - step: "Проверка поля для ввода логина"
      description: "Убедитесь, что поле для ввода логина отображается корректно и доступно для ввода."
      expected_result: "Поле для ввода логина видно, доступно и не имеет ошибок."

    - step: "Проверка поля для ввода пароля"
      description: "Убедитесь, что поле для ввода пароля отображается корректно и доступно для ввода."
      expected_result: "Поле для ввода пароля видно, доступно и не имеет ошибок."

    - step: "Проверка минимальной длины пароля"
      description: "Убедитесь, что пароль не может быть короче минимально установленной длины."
      expected_result: "При вводе пароля, который короче минимальной длины, появляется ошибка с сообщением о минимальной длине."

    - step: "Проверка длины логина"
      description: "Убедитесь, что логин не может быть короче минимальной длины."
      expected_result: "При вводе логина, который короче минимальной длины, появляется ошибка с сообщением о минимальной длине."

    - step: "Проверка символов в логине"
      description: "Убедитесь, что логин может содержать только допустимые символы (например, буквы и цифры)."
      expected_result: "При вводе недопустимых символов появляется ошибка с соответствующим сообщением."

    - step: "Проверка безопасности пароля"
      description: "Убедитесь, что пароль должен содержать как минимум одну заглавную букву, цифру и специальный символ."
      expected_result: "При вводе пароля без одного из требуемых символов появляется ошибка с соответствующим сообщением."

    - step: "Проверка подсказки для пароля"
      description: "Убедитесь, что при вводе пароля появляется подсказка о требованиях к паролю."
      expected_result: "Подсказка отображается, если пользователь еще не ввел правильный пароль."

    - step: "Проверка соответствия пароля и подтверждения пароля"
      description: "Убедитесь, что при регистрации пароль и подтверждение пароля совпадают."
      expected_result: "При несовпадении паролей появляется ошибка с соответствующим сообщением."

    - step: "Проверка успешного входа"
      description: "Убедитесь, что при вводе правильных логина и пароля пользователь успешно входит в систему."
      expected_result: "Пользователь перенаправляется на страницу профиля или главную страницу после успешного входа."

    - step: "Проверка ошибки при неверных данных"
      description: "Убедитесь, что при вводе неверного логина или пароля появляется ошибка."
      expected_result: "При неверном логине или пароле появляется сообщение о неправильных данных."
