title: "Login Field Validation Checklist"
description: "Checklist for validating the login fields functionality on the login page."

steps:
  - step: "Проверка наличия обязательных полей"
    description:
      - "Убедитесь, что поле 'Логин' отображается на странице."
      - "Убедитесь, что поле 'Пароль' отображается на странице."

  - step: "Проверка типов данных"
    description:
      - "Логин:"
        - "Проверьте, что поле логина принимает только текст (без чисел, специальных символов, если это предусмотрено)."
        - "Проверьте, что поле логина ограничивает количество символов в соответствии с требованиями (например, от 3 до 50 символов)."
      - "Пароль:"
        - "Убедитесь, что поле пароля скрывает введенные символы."
        - "Проверьте, что поле пароля позволяет вводить комбинации символов (буквы, цифры, спецсимволы) в соответствии с политикой безопасности (например, минимум 8 символов, одна заглавная буква, одна цифра и спецсимвол)."

  - step: "Проверка обязательности полей"
    description:
      - "Проверьте, что поле логина не может быть оставлено пустым."
      - "Проверьте, что поле пароля не может быть оставлено пустым."
      - "Убедитесь, что при отсутствии данных в любом из полей появляется сообщение об ошибке, например, 'Поле не может быть пустым'."

  - step: "Проверка формата ввода"
    description:
      - "Логин:"
        - "Убедитесь, что поле принимает корректные форматы (например, email или имя пользователя)."
        - "Проверьте, что поле не принимает пробелы в начале или в конце."
      - "Пароль:"
        - "Проверьте, что поле пароля требует минимальной длины (например, 8 символов)."
        - "Убедитесь, что поле пароля не позволяет использовать слишком простые пароли (например, '12345678')."

  - step: "Проверка кнопки 'Войти'"
    description:
      - "Убедитесь, что кнопка 'Войти' активна только тогда, когда оба поля заполнены корректно."
      - "Убедитесь, что кнопка 'Войти' неактивна (или не доступна для нажатия), если одно из полей не заполнено или заполнено неверно."

  - step: "Проверка сообщений об ошибке"
    description:
      - "При вводе неверных данных (например, неверный логин или пароль), убедитесь, что появляется корректное сообщение об ошибке."
      - "Проверьте, что сообщения об ошибке информативны, например, 'Неверный логин или пароль' или 'Введите правильный логин'."

  - step: "Проверка восстановления пароля"
    description:
      - "Убедитесь, что на странице логина есть ссылка для восстановления пароля."
      - "Проверьте, что ссылка корректно ведет на страницу восстановления пароля."

  - step: "Проверка кросс-браузерной совместимости"
    description:
      - "Проверьте, что поля логина и пароля корректно отображаются и работают в различных браузерах (Chrome, Firefox, Safari, Edge и т.д.)."

  - step: "Проверка работы кнопки 'Запомнить меня' (если предусмотрена)"
    description:
      - "Проверьте, что чекбокс 'Запомнить меня' работает корректно."
      - "Убедитесь, что при включении чекбокса пользователь остаётся авторизованным после перезагрузки страницы (если это предусмотрено)."

  - step: "Проверка безопасности"
    description:
      - "Убедитесь, что поле пароля не показывает введенные символы при нажатии на глазик (если это предусмотрено)."
      - "Проверьте, что приложение защищает от атак типа 'brute force' (ограничение количества попыток входа)."
