## Чек-лист для тестирования страницы

- [ ] Проверить, что страница загружается корректно
- [ ] Проверить адаптивность дизайна (проверить на различных устройствах)
- [ ] Проверить функциональность всех кнопок
- [ ] Проверить все ссылки на наличие 404 ошибок
- [ ] Проверить доступность страницы (наличие alt-тегов для изображений, доступность для экранных читалок)
- [ ] Проверить валидацию форм (обязательные поля, сообщения об ошибках)
- [ ] Проверить выравнивание и отступы элементов
- [ ] Проверить актуальность контента
