tests:
  - description: "Проверка поля для ввода логина"
    steps:
      - action: "Убедитесь, что поле для ввода логина отображается корректно и доступно для ввода."
        expected_result: "Поле для ввода логина видно, доступно и не имеет ошибок."
