checklist:
  - item: "Check if the page loads correctly"
    description: "Ensure that the page is accessible and loads within 3 seconds."
    status: "not started"
    priority: "high"
  - item: "Verify responsive design"
    description: "Ensure the layout adjusts correctly on various screen sizes."
    status: "in progress"
    priority: "medium"
  - item: "Test all buttons for functionality"
    description: "Click all buttons to ensure they lead to the correct destinations."
    status: "completed"
    priority: "high"
