login_password_validation:
  - step: "Проверка поля для ввода логина"
    description: "Убедитесь, что поле для ввода логина отображается корректно и доступно для ввода."
    expected_result: "Поле для ввода логина видно, доступно и не имеет ошибок."

