steps:
  - name: "Проверка поля для ввода логина"
    description: "Убедитесь, что поле для ввода логина отображается корректно и доступно для ввода."
    result: "Поле для ввода логина видно, доступно и не имеет ошибок."
