name: Task
description: Template for creating a new task
title: "[TASK] "
labels: task
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Пожалуйста, заполните следующую информацию для новой задачи:**

  - type: input
    id: summary
    attributes:
      label: "Краткое описание задачи"
      description: "Введите краткое описание или цель задачи"
      placeholder: "Например, Обновить страницу профиля пользователя"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Подробное описание задачи"
      description: "Опишите, что нужно сделать в рамках задачи"
      placeholder: "Введите детали задачи, шаги для выполнения и ожидаемые результаты"
    validations:
      required: true

  - type: input
    id: due_date
    attributes:
      label: "Срок выполнения
