name: Task_n
description: Template for creating a new task
title: "[TASK] "
labels: 
  - task
assignees: []  # Leave blank to allow assignment later

body:
  - type: markdown
    attributes:
      value: |
        **Please fill out the following information for the new task:**

  - type: input
    id: task_summary
    attributes:
      label: "Task Summary"
      description: "Provide a brief summary or goal for the task"
      placeholder: "e.g., Update user profile page"
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: "Detailed Task Description"
      description: "Describe what needs to be done in detail, steps for completion, and expected outcomes"
      placeholder: "Enter task details, steps, and expected outcomes"
    validations:
      required: true

  - type: input
    id: task_due_date
    attributes:
      label: "Due Date"
      description: "Specify the deadline for this task (e.g., 2024-12-31)"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: checkboxes
    id: task_priority
    attributes:
      label: "Priority"
      description: "Select the priority level for the task"
      options:
        - label: High
        - label: Medium
        - label: Low
    validations:
      required: true

  - type: dropdown
  id: task_status
  attributes:
    label: "Task Status"
    description: "Specify the current status of the task"
    options:
      - label: "To Do"
      - label: "In Progress"
      - label: "Done"
  validations:
    required: true

  - type: textarea
    id: task_additional_notes
    attributes:
      label: "Additional Notes"
      description: "Any additional information or links that might be useful"
      placeholder: "Enter any additional comments or notes"
    validations:
      required: false
