name: Test Case
description: Template for creating a new TC
title: "[TC] "
labels:
  - task
assignees: []  # Leave blank to allow assignment later

body:
  - type: markdown
    attributes:
      value: |
        **Test Case (TC) Details:**

  - type: input
    id: tc_id
    attributes:
      label: "Test Case ID"
      description: "Unique identifier for the test case"
      placeholder: "TC_000.000.000"
    validations:
      required: true

  - type: textarea
    id: tc_description
    attributes:
      label: "Description"
      description: "Overview of the test case"
      placeholder: "Enter description of the test case"
    validations:
      required: true

  - type: textarea
    id: tc_preconditions
    attributes:
      label: "Preconditions"
      description: "Any conditions that must be met before executing the test"
      placeholder: "Enter preconditions"
    validations:
      required: true

  - type: textarea
    id: tc_steps
    attributes:
      label: "Steps"
      description: "Steps to execute the test case"
      placeholder: "Enter test case steps"
    validations:
      required: true

  - type: textarea
    id: tc_expected_results
    attributes:
      label: "Expected Results"
      description: "The expected outcome after executing the test case"
      placeholder: "Enter expected results"
    validations:
      required: true

  - type: textarea
    id: tc_notifications
    attributes:
      label: "Notifications"
      description: "Any notifications related to the test case"
      placeholder: "Enter notifications"
    validations:
      required: false
