name: Test Case 
description: Use this template to create a new test case
title: "TC_00.000.000 | "
labels: ["test-case"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Please update the issue title above with the correct test case ID and name**  
            ID Format: ` TC_XX.YYY.ZZ | Epic Name > User Story Name > Test Case Name`

        Please fill out the following fields:

  - type: textarea
    id: precondition
    attributes:
      label: "Precondition"
      description: "What needs to be set up before the test"
    validations:
      required: true  

  - type: textarea
    id: tc_steps
    attributes:
      label: "Steps"
      description: "Steps to execute the test case"
      placeholder: |
        1. Go to the main page
        2. Click on 'Submit a request'
        3. Fill in the form
        4. Click 'Send'
    validations:
      required: true

  - type: textarea
    id: tc_expected_results
    attributes:
      label: "Expected Results"
      description: "What should happen"
      placeholder: "Enter expected results"
    validations:
      required: true
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: |
        By [Action/Trigger], the user can access [Feature/Functionality].  
        Clicking on [Element] opens [Page/Section], where [Feature/Functionality] is also available in [Location].
    validations:
      required: false
