name: Test Case 
description: Use this template to create a new test case

body:
  - type: input
    id: tc_details
    attributes:
      label: "Test Case"
      description: "Enter both Test Case ID and Title in the format: TC_00.000.000 | Epic Name > User Story Name > Test Case Name"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Please provide details for the test case:
          
  - type: textarea
    id: precondition
    attributes:
      label: "Precondition"
      description: "What needs to be set up before the test"
    validations:
      required: true  

  - type: textarea
    id: tc_expected_results
    attributes:
      label: "Expected Results"
      description: "What should happen"
      placeholder: "Enter expected results"
    validations:
      required: true
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: 
        'By [Action/Trigger], the user can access [Feature/Functionality].  
        /nClicking on [Element] opens [Page/Section], where [Feature/Functionality] is also available in [Location].'
    validations:
      required: false
