name: Test Case 
description: Use this template to create a new test case
title: "[Test Case] <Enter test case title>"
labels: ["test-case"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide details for the test case:
  - type: input
    id: test-case-id
    attributes:
      label: Test Case ID
      description: Unique identifier for the test case
      placeholder: "Enter the test case ID"
    validations:
      required: true
body:
  - type: input
    id: tc_details
    attributes:
      label: "Test Case"
      description: "Enter both Test Case ID and Title in the format: TC_000.000.000 | US title > Test Case Name"
      # placeholder: "TC_011.017.001|Sale>Multiple discounts > Purchase more than $200"
    validations:
      required: true

  # - type: textarea
  #   attributes:
  #     value: |
  #       **Preconditions:**
  - type: textarea
    id: precondition
    attributes:
      label: "Steps"
      description: "Steps to execute the test case"
      placeholder: "Enter precondition"
    validations:
      required: true      
  # - type: dropdown
  #   id: browsers
  #   attributes:
  #     label: "Browsers"
  #     description: "What browsers do you see the problem on?"
    #   multiple: true
    #   options:
    #     - Firefox
    #     - Chrome
    #     - Safari
    #     - Microsoft Edge
    #     - Opera
    # validations:
    #   required: false

  # - type: dropdown
  #   id: os
  #   attributes:
  #     label: "OS"
  #     description: "What is the impacted environment?"
  #     multiple: false
  #     options:
  #       - Windows
  #       - Linux
  #       - Mac
  #   validations:
  #     required: false

  - type: textarea
    id: tc_steps
    attributes:
      label: "Steps"
      description: "Steps to execute the test case"
      placeholder: "Enter test case steps"
    validations:
      required: true

  - type: textarea
    id: tc_expected_results
    attributes:
      label: "Expected Results"
      description: "The expected outcome after executing the test case"
      placeholder: "Enter expected results"
    validations:
      required: true
