name: Test Case Template
description: |
  The test case includes Acceptance Criteria in textual form, which it covers. 
  This allows for a clear understanding of the specific requirements being verified by the test case.
labels: Test Case
assignees: me


body:
  - type: markdown
    attributes:
      value: '**ID**: TC_XX.YYY.ZZ | Epic Name > User Story Name > Test Case Name'

  - type: textarea
    id: id_test_case
    attributes:
      label: Test case 
      placeholder: |
         ID: TC_XX.YYY.ZZ | Epic Name > User Story Name > Test Case Name
    validations:
      required: True

  - type: textarea
    id: precondition
    attributes:
      label: Precondition
      description: |
        What needs to be set up before the test
    validations:
      required: True

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the test case
    validations:
      required: True

  - type: textarea
    id: Steps
    attributes:
      label: Steps
      placeholder: |
        1. Open the application
        2. Enter username and password  
        3. Click on the login button
        4. Verify that the user is redirected to the dashboard
    validations:
      required: True

  - type: textarea
    id: expected_result
    attributes:
      label: Expected Result
      description: What should happen  
    validations:
      required: True

  - type: textarea
    id: acceptence_criteria
    attributes:
      label: Acceptence Criteria
      description: |
        By [Action/Trigger], the user can access [Feature/Functionality].  
        Clicking on [Element] opens [Page/Section], where [Feature/Functionality] is also available in [Location].
    validations:
      required: True
  


   



