name: Test Case
description: Template for creating a new TC
title: "{{tc_id}} | {{tc_title}}"  # Combine TC ID and descriptive title in one line
labels:
  - task
assignees: []  # Leave blank to allow assignment later

body:
  - type: markdown
    attributes:
      value: |
        **Test Case (TC) Details:**

  - type: input
    id: tc_id
    attributes:
      label: "Test Case ID"
      description: "Unique identifier for the test case"
      placeholder: "TC_000.000.000"
    validations:
      required: true

  - type: input
    id: tc_title
    attributes:
      label: "Test Case Title"
      description: "A brief title or description for the test case"
      placeholder: "Sale > Multiple discounts > Purchase more than $200"
    validations:
      required: true

  - type: textarea
    id: tc_preconditions
    attributes:
      label: "Preconditions"
      description: "Any conditions that must be met before executing the test"
      placeholder: "Enter preconditions"
    validations:
      required: true

  - type: textarea
    id: tc_steps
    attributes:
      label: "Steps"
      description: "Steps to execute the test case"
      placeholder: "Enter test case steps"
    validations:
      required: true

  - type: textarea
    id: tc_expected_results
    attributes:
      label: "Expected Results"
      description: "The expected outcome after executing the test case"
      placeholder: "Enter expected results"
    validations:
      required: true

  - type: input
    id: tc_screenshot_url
    attributes:
      label: "Screenshot URL"
      description: "Provide a URL to the screenshot"
      placeholder: "Enter screenshot URL"
    validations:
      required: false
