name: Web Interface Bug Report
description: Something doesn't look quite as it should? Report it here!
labels: ["type/bug", "topic/ui"]
body:
  - type: markdown
    attributes:
      value: |
        **ID**: TC_XX.YYY.ZZ  
        **Epic Name** > **User Story Name** > **Test Case Name**

  - type: textarea
    id: precondition
    attributes:
      label: Precondition
      description: |
        What needs to be set up before the test
    validations:
      required: True

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the test case
    validations:
      required: True

  - type: textarea
    id: Steps
    attributes:
      label: Steps
      placeholder: |
        1.  
        2.  
        3. 
    labels: 
    - TC
    validations:
      required: True


