name: Web Interface Bug Report
description: Something doesn't look quite as it should? Report it here!
labels: ["type/bug", "topic/ui"]
body:
  - type: markdown
    attributes:
      value: |
        **ID**: TC_XX.YYY.ZZ  
        **Epic Name** > **User Story Name** > **Test Case Name**

# ID: TC_XX.YYY.ZZ | Epic Name > User Story Name > Test Case Name

# Preconditions: (What needs to be set up before the test)

# Description: (Brief description of the test case)

# Steps:

# [Step 1]
# [Step 2]
# [Step 3]
# Expected Result: (What should happen)

# Comments / Notes: (Additional details, attachments, logs)

# Acceptance Criteria:

# By [Action/Trigger], the user can access [Feature/Functionality].
# Clicking on [Element] opens [Page/Section], where [Feature/Functionality] is also available in [Location].

  - type: textarea
    id: precondition
    attributes:
      label: Precondition
      description: |
        What needs to be set up before the test
    validations:
      required: True
        
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please provide at least 1 screenshot showing the issue.
    validations:
      required: False

  # - type: input
  #   id: gitea-ver
  #   attributes:
  #     label: Gitea Version
  #     description: Gitea version (or commit reference) your instance is running
  #   validations:
  #     required: False

  # - type: dropdown
  #   id: can-reproduce
  #   attributes:
  #     label: Can you reproduce the bug on the Gitea demo site?
  #     description: |
  #       If so, please provide a URL in the Description field
  #       URL of Gitea demo: https://demo.gitea.com
  #     options:
  #       - "Yes"
  #       - "No"
  #   validations:
  #     required: False

  # - type: input
  #   id: os-ver
  #   attributes:
  #     label: Operating System
  #     description: The operating system you are using to access Gitea

  # - type: input
  #   id: browser-ver
  #   attributes:
  #     label: Browser Version
  #     description: The browser and version that you are using to access Gitea
  #   validations:
      required: False
