test_case:
  title: Проверка создания репозитория из шаблона на GitHub
  id: TC-001
  description: Этот тест проверяет возможность создания нового репозитория с использованием шаблона.
  preconditions:
    - Пользователь авторизован на GitHub.
    - Шаблон репозитория доступен для использования.
  test_steps:
    - step: Перейти на страницу создания нового репозитория.
      expected_result: Страница создания репозитория открыта.
    - step: Выбрать шаблон из списка доступных шаблонов.
      expected_result: Шаблон выбран, и структура репозитория загружена.
    - step: Ввести название нового репозитория и описание.
      expected_result: Репозиторий назван и описан.
    - step: Нажать кнопку "Создать репозиторий".
      expected_result: Репозиторий создан и отображается на странице.
  postconditions:
    - Новый репозиторий создан и отображается в списке репозиториев пользователя.
  expected_result: Репозиторий успешно создан из шаблона с заданным названием и описанием.
  status: Passed
  priority: High
  created_by: Иван Иванов
  created_on: 2024-11-05
