user_story:
  title: Шаблон для создания репозитория в Git
  as_a: разработчик
  i_want_to: иметь шаблон репозитория в Git
  so_that: быстро создавать новые проекты с одинаковой структурой и стандартами кода

acceptance_criteria:
  - Шаблон должен включать базовые файлы: 

additional_notes:
  - Нужно обеспечить, чтобы шаблон был совместим с несколькими языками программирования (например, Python, JavaScript)
  - Для документации использовать стандартный формат Markdown
