user_story:
  title: Шаблон для создания репозитория в Git
  as_a: разработчик
  i_want_to: иметь шаблон репозитория в Git
  so_that: быстро создавать новые проекты с одинаковой структурой и стандартами кода

acceptance_criteria:
  - Шаблон должен включать базовые файлы: "README.md", ".gitignore", "LICENSE"
  - В шаблоне должна быть структура каталогов, подходящая для начальной настройки проекта
  - Шаблон должен содержать базовые настройки CI/CD (если применимо)
  - Шаблон должен иметь примеры начальных файлов кода (например, файл "index.js" для JS проектов)
  - Репозиторий должен быть доступен для использования в качестве шаблона при создании нового репозитория на GitHub

additional_notes:
  - Нужно обеспечить, чтобы шаблон был совместим с несколькими языками программирования (например, Python, JavaScript)
  - Для документации использовать стандартный формат Markdown
